-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 10:52:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema twitter_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `twitter_db` ;

-- -----------------------------------------------------
-- Schema twitter_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twitter_db` DEFAULT CHARACTER SET utf8 ;
USE `twitter_db` ;

-- -----------------------------------------------------
-- Table `twitter_db`.`tweets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_db`.`tweets` ;

CREATE TABLE IF NOT EXISTS `twitter_db`.`tweets` (
  `tweet_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `tweet_info` JSON NULL,
  `created_datetime` DATETIME NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tweet_id`),
  INDEX `fk_tweets_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tweets_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `twitter_db`.`user_info` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_db`.`user_authorization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_db`.`user_authorization` ;

CREATE TABLE IF NOT EXISTS `twitter_db`.`user_authorization` (
  `auth_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `last_synced_tweet_id` INT NULL,
  `last_synced_time` DATETIME NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_datetime` DATETIME NOT NULL,
  `modified_by` VARCHAR(45) NULL,
  `modified_datetime` DATETIME NULL,
  PRIMARY KEY (`auth_id`),
  INDEX `fk_auth_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `twitter_db`.`user_info` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_db`.`user_authorization_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_db`.`user_authorization_history` ;

CREATE TABLE IF NOT EXISTS `twitter_db`.`user_authorization_history` (
  `auth_history_id` VARCHAR(45) NOT NULL,
  `auth_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `last_synced_tweet_id` INT NULL,
  `last_synced_time` DATETIME NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`auth_history_id`),
  INDEX `fk_auth_history_auth_id_idx` (`auth_id` ASC) VISIBLE,
  CONSTRAINT `fk_auth_history_auth_id`
    FOREIGN KEY (`auth_id`)
    REFERENCES `twitter_db`.`user_authorization` (`auth_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter_db`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_db`.`user_info` ;

CREATE TABLE IF NOT EXISTS `twitter_db`.`user_info` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_datetime` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_name_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
